In [2]:
import pypsa
import pandas as pd

n = pypsa.Network()

In [3]:
n.add("Bus", "bus_1", v_nom=11)
n.add("Bus", "bus_2", v_nom=11)
n.add("Bus", "bus_3", v_nom=11)

In [4]:
n.add("Load", "load_1", bus="bus_1", p_set=500)

n.add(
    "Generator",
    "coal",
    bus="bus_1",
    p_nom=300,
    p_min_pu=50/300,
    marginal_cost=3,
)

In [5]:
n.add(
    "Generator",
    "gas",
    bus="bus_2",
    p_nom=400,
    p_min_pu=100/400,
    marginal_cost=4,
)

In [6]:
n.add("Load", "load_3", bus="bus_3", p_set=0)

n.add(
    "Generator",
    "solar",
    bus="bus_3",
    p_nom=300,
    marginal_cost=0,
)

In [7]:
n.set_snapshots(pd.date_range("2025-01-01", periods=24, freq="h"))

n.generators_t.p_max_pu["solar"] = [
    0, 0, 0, 0, 0, 0,
    0.1, 0.3, 0.5, 0.7, 0.9, 1.0,
    1.0, 0.9, 0.7, 0.5, 0.3, 0.1,
    0, 0, 0, 0, 0, 0
]

n.loads_t.p_set["load_3"] = [100, 100, 100, 100, 120, 120,
                             150, 180, 200, 200, 200, 200,
                             180, 180, 180, 200, 200, 200,
                             200, 200, 200, 200, 150, 120]

In [8]:
n.add(
    "Line",
    "line_1",
    bus0="bus_1",
    bus1="bus_2",
    x=0.1,
    r=0.01,
    s_nom=200,
)

n.add(
    "Line",
    "line_2",
    bus0="bus_2",
    bus1="bus_3",
    x=0.1,
    r=0.01,
    s_nom=200,
)

n.add(
    "Line",
    "line_3",
    bus0="bus_3",
    bus1="bus_1",
    x=0.1,
    r=0.01,
    s_nom=150,
)

In [9]:
n.optimize()

WARNING:pypsa.consistency:The following lines have carriers which are not defined:
Index(['line_1', 'line_2', 'line_3'], dtype='object', name='Line')
WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['bus_1', 'bus_2', 'bus_3'], dtype='object', name='Bus')
WARNING:pypsa.consistency:The following lines have carriers which are not defined:
Index(['line_1', 'line_2', 'line_3'], dtype='object', name='Line')
WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['bus_1', 'bus_2', 'bus_3'], dtype='object', name='Bus')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io: Writing time: 0.02s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 144 primals, 384 duals
Objective: 4.83e+04
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Line-fix-s-lower, Line-fix-s-upper, Kirchhoff-Voltage-Law were not assigned to the network.

Running HiGHS 1.11.0 (git hash: n/a): Copyright (c) 2025 HiGHS under MIT licence terms
LP   linopy-problem-cwe4jps_ has 384 rows; 144 cols; 576 nonzeros
Coefficient ranges:
  Matrix [1e+00, 8e+01]
  Cost   [3e+00, 4e+00]
  Bound  [0e+00, 0e+00]
  RHS    [3e+01, 5e+02]
Presolving model
72 rows, 108 cols, 192 nonzeros  0s
42 rows, 66 cols, 127 nonzeros  0s
Dependent equations search running on 34 equations with time limit of 1000.00s
Dependent equations search removed 0 rows and 0 nonzeros in 0.00s (limit = 1000.00s)
34 rows, 56 cols, 102 nonzeros  0s
Presolve : Reductions: rows 34(-350); columns 56(-88); elements 102(-474)
Solving the presolved LP
Using EKK dual simplex solver - serial
  Iteration        Objective     Infeasibilities num(sum)
          0     3.5430031193e+04 Pr: 34(40555.5) 0s
         42     4.8340000000e+04 Pr: 0(0) 0s
Solving the original LP from the solution after postsolve
Model name          : linopy-problem-cwe4jps_
Model status        : Optimal
Simplex   iterations: 42
Objective value     :  4.8340000000e+04
P-D objective error :  0.0000000000e+00
HiGHS run time      :          0.01
Writing the solution to /tmp/linopy-solve-p3mhn6tr.sol

('ok', 'optimal')

In [10]:
n.generators_t.p

Generator             coal    gas  solar
snapshot
2025-01-01 00:00:00  300.0  300.0   -0.0
2025-01-01 01:00:00  300.0  300.0   -0.0
2025-01-01 02:00:00  300.0  300.0   -0.0
2025-01-01 03:00:00  300.0  300.0   -0.0
2025-01-01 04:00:00  300.0  320.0   -0.0
2025-01-01 05:00:00  300.0  320.0   -0.0
2025-01-01 06:00:00  300.0  320.0   30.0
2025-01-01 07:00:00  300.0  290.0   90.0
2025-01-01 08:00:00  300.0  250.0  150.0
2025-01-01 09:00:00  300.0  190.0  210.0
2025-01-01 10:00:00  300.0  130.0  270.0
2025-01-01 11:00:00  300.0  100.0  300.0
2025-01-01 12:00:00  280.0  100.0  300.0
2025-01-01 13:00:00  300.0  110.0  270.0
2025-01-01 14:00:00  300.0  170.0  210.0
2025-01-01 15:00:00  300.0  250.0  150.0
2025-01-01 16:00:00  300.0  310.0   90.0
2025-01-01 17:00:00  300.0  370.0   30.0
2025-01-01 18:00:00  300.0  400.0   -0.0
2025-01-01 19:00:00  300.0  400.0   -0.0
2025-01-01 20:00:00  300.0  400.0   -0.0
2025-01-01 21:00:00  300.0  400.0   -0.0
2025-01-01 22:00:00  300.0  350.0   -0.0
2025-01-01 23:00:00  300.0  320.0   -0.0

In [11]:
n.pf()

INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 01:00:00',
               '2025-01-01 02:00:00', '2025-01-01 03:00:00',
               '2025-01-01 04:00:00', '2025-01-01 05:00:00',
               '2025-01-01 06:00:00', '2025-01-01 07:00:00',
               '2025-01-01 08:00:00', '2025-01-01 09:00:00',
               '2025-01-01 10:00:00', '2025-01-01 11:00:00',
               '2025-01-01 12:00:00', '2025-01-01 13:00:00',
               '2025-01-01 14:00:00', '2025-01-01 15:00:00',
               '2025-01-01 16:00:00', '2025-01-01 17:00:00',
               '2025-01-01 18:00:00', '2025-01-01 19:00:00',
               '2025-01-01 20:00:00', '2025-01-01 21:00:00',
               '2025-01-01 22:00:00', '2025-01-01 23:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq='h')
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.011490 seconds
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.012520 seconds
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.009683 seconds
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.008608 seconds
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.008969 seconds
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.008904 seconds
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.009000 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.011712 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.012130 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.011884 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.012033 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.011725 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.014266 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.012634 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.011385 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.011277 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.014404 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.021764 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.012531 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.012188 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.011767 seconds
INFO:pypsa.pf:Newton-Raphson solved in 4 iterations with error of 0.000000 in 0.013337 seconds
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.009243 seconds
INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.009036 seconds

{'n_iter': SubNetwork           0
 snapshot
 2025-01-01 00:00:00  3
 2025-01-01 01:00:00  3
 2025-01-01 02:00:00  3
 2025-01-01 03:00:00  3
 2025-01-01 04:00:00  3
 2025-01-01 05:00:00  3
 2025-01-01 06:00:00  3
 2025-01-01 07:00:00  4
 2025-01-01 08:00:00  4
 2025-01-01 09:00:00  4
 2025-01-01 10:00:00  4
 2025-01-01 11:00:00  4
 2025-01-01 12:00:00  4
 2025-01-01 13:00:00  4
 2025-01-01 14:00:00  4
 2025-01-01 15:00:00  4
 2025-01-01 16:00:00  4
 2025-01-01 17:00:00  4
 2025-01-01 18:00:00  4
 2025-01-01 19:00:00  4
 2025-01-01 20:00:00  4
 2025-01-01 21:00:00  4
 2025-01-01 22:00:00  3
 2025-01-01 23:00:00  3,
 'error': SubNetwork                      0
 snapshot
 2025-01-01 00:00:00  1.001833e-08
 2025-01-01 01:00:00  1.001833e-08
 2025-01-01 02:00:00  1.001833e-08
 2025-01-01 03:00:00  1.001833e-08
 2025-01-01 04:00:00  4.464140e-08
 2025-01-01 05:00:00  4.464140e-08
 2025-01-01 06:00:00  2.817680e-07
 2025-01-01 07:00:00  2.257865e-13
 2025-01-01 08:00:00  8.393199e-13
 2025-01-01 09:00:00  8.393199e-13
 2025-01-01 10:00:00  8.393199e-13
 2025-01-01 11:00:00  8.393199e-13
 2025-01-01 12:00:00  2.257865e-13
 2025-01-01 13:00:00  2.257865e-13
 2025-01-01 14:00:00  2.257865e-13
 2025-01-01 15:00:00  8.393199e-13
 2025-01-01 16:00:00  8.393199e-13
 2025-01-01 17:00:00  8.393199e-13
 2025-01-01 18:00:00  8.393199e-13
 2025-01-01 19:00:00  8.393199e-13
 2025-01-01 20:00:00  8.393199e-13
 2025-01-01 21:00:00  8.393199e-13
 2025-01-01 22:00:00  2.817680e-07
 2025-01-01 23:00:00  4.464140e-08,
 'converged': SubNetwork              0
 snapshot
 2025-01-01 00:00:00  True
 2025-01-01 01:00:00  True
 2025-01-01 02:00:00  True
 2025-01-01 03:00:00  True
 2025-01-01 04:00:00  True
 2025-01-01 05:00:00  True
 2025-01-01 06:00:00  True
 2025-01-01 07:00:00  True
 2025-01-01 08:00:00  True
 2025-01-01 09:00:00  True
 2025-01-01 10:00:00  True
 2025-01-01 11:00:00  True
 2025-01-01 12:00:00  True
 2025-01-01 13:00:00  True
 2025-01-01 14:00:00  True
 2025-01-01 15:00:00  True
 2025-01-01 16:00:00  True
 2025-01-01 17:00:00  True
 2025-01-01 18:00:00  True
 2025-01-01 19:00:00  True
 2025-01-01 20:00:00  True
 2025-01-01 21:00:00  True
 2025-01-01 22:00:00  True
 2025-01-01 23:00:00  True}

In [12]:
n.lines_t.p0

                        line_1     line_2      line_3
snapshot
2025-01-01 00:00:00  33.519620  33.426477  -66.666667
2025-01-01 01:00:00  33.519620  33.426477  -66.666667
2025-01-01 02:00:00  33.519620  33.426477  -66.666667
2025-01-01 03:00:00  33.519620  33.426477  -66.666667
2025-01-01 04:00:00  40.269233  40.134616  -80.000000
2025-01-01 05:00:00  40.269233  40.134616  -80.000000
2025-01-01 06:00:00  50.423208  50.211604 -100.000000
2025-01-01 07:00:00  60.613493  60.306747 -120.000000
2025-01-01 08:00:00  67.427728  67.047197 -133.333333
2025-01-01 09:00:00  67.427728  67.047197 -133.333333
2025-01-01 10:00:00  67.427728  67.047197 -133.333333
2025-01-01 11:00:00  67.427728  67.047197 -133.333333
2025-01-01 12:00:00  60.613493  60.306747 -120.000000
2025-01-01 13:00:00  60.613493  60.306747 -120.000000
2025-01-01 14:00:00  60.613493  60.306747 -120.000000
2025-01-01 15:00:00  67.427728  67.047197 -133.333333
2025-01-01 16:00:00  67.427728  67.047197 -133.333333
2025-01-01 17:00:00  67.427728  67.047197 -133.333333
2025-01-01 18:00:00  67.427728  67.047197 -133.333333
2025-01-01 19:00:00  67.427728  67.047197 -133.333333
2025-01-01 20:00:00  67.427728  67.047197 -133.333333
2025-01-01 21:00:00  67.427728  67.047197 -133.333333
2025-01-01 22:00:00  50.423208  50.211604 -100.000000
2025-01-01 23:00:00  40.269233  40.134616  -80.000000

In [13]:
n.lines_t.p1

                        line_1     line_2      line_3
snapshot
2025-01-01 00:00:00 -33.426477 -33.333333   67.039240
2025-01-01 01:00:00 -33.426477 -33.333333   67.039240
2025-01-01 02:00:00 -33.426477 -33.333333   67.039240
2025-01-01 03:00:00 -33.426477 -33.333333   67.039240
2025-01-01 04:00:00 -40.134617 -40.000000   80.538466
2025-01-01 05:00:00 -40.134617 -40.000000   80.538466
2025-01-01 06:00:00 -50.211604 -50.000000  100.846417
2025-01-01 07:00:00 -60.306747 -60.000000  121.226986
2025-01-01 08:00:00 -67.047197 -66.666667  134.855456
2025-01-01 09:00:00 -67.047197 -66.666667  134.855456
2025-01-01 10:00:00 -67.047197 -66.666667  134.855456
2025-01-01 11:00:00 -67.047197 -66.666667  134.855456
2025-01-01 12:00:00 -60.306747 -60.000000  121.226986
2025-01-01 13:00:00 -60.306747 -60.000000  121.226986
2025-01-01 14:00:00 -60.306747 -60.000000  121.226986
2025-01-01 15:00:00 -67.047197 -66.666667  134.855456
2025-01-01 16:00:00 -67.047197 -66.666667  134.855456
2025-01-01 17:00:00 -67.047197 -66.666667  134.855456
2025-01-01 18:00:00 -67.047197 -66.666667  134.855456
2025-01-01 19:00:00 -67.047197 -66.666667  134.855456
2025-01-01 20:00:00 -67.047197 -66.666667  134.855456
2025-01-01 21:00:00 -67.047197 -66.666667  134.855456
2025-01-01 22:00:00 -50.211604 -50.000000  100.846417
2025-01-01 23:00:00 -40.134617 -40.000000   80.538466

In [14]:
display((n.lines_t.p0 + n.lines_t.p1).sum().sum())  # active power losses

39.67472302132783

In [15]:
losses = n.lines_t.p0 + n.lines_t.p1
losses.sum(axis=1)

snapshot
2025-01-01 00:00:00    0.558860
2025-01-01 01:00:00    0.558860
2025-01-01 02:00:00    0.558860
2025-01-01 03:00:00    0.558860
2025-01-01 04:00:00    0.807699
2025-01-01 05:00:00    0.807699
2025-01-01 06:00:00    1.269625
2025-01-01 07:00:00    1.840479
2025-01-01 08:00:00    2.283183
2025-01-01 09:00:00    2.283183
2025-01-01 10:00:00    2.283183
2025-01-01 11:00:00    2.283183
2025-01-01 12:00:00    1.840479
2025-01-01 13:00:00    1.840479
2025-01-01 14:00:00    1.840479
2025-01-01 15:00:00    2.283183
2025-01-01 16:00:00    2.283183
2025-01-01 17:00:00    2.283183
2025-01-01 18:00:00    2.283183
2025-01-01 19:00:00    2.283183
2025-01-01 20:00:00    2.283183
2025-01-01 21:00:00    2.283183
2025-01-01 22:00:00    1.269625
2025-01-01 23:00:00    0.807699
Freq: h, dtype: float64

In [16]:
m = n.model
m.variables
m.constraints

linopy.model.Constraints
------------------------
 * Generator-fix-p-lower (snapshot, Generator-fix)
 * Generator-fix-p-upper (snapshot, Generator-fix)
 * Line-fix-s-lower (snapshot, Line-fix)
 * Line-fix-s-upper (snapshot, Line-fix)
 * Bus-nodal_balance (Bus, snapshot)
 * Kirchhoff-Voltage-Law (snapshot, cycles)

In [17]:
m.to_file("pypsa_dispatch_1.lp")

INFO:linopy.io: Writing time: 0.03s

PosixPath('pypsa_dispatch_1.lp')

In [18]:
m.solve(solver_name="highs", output_flag=False)

INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.model:Solver options:
 - output_flag: False
INFO:linopy.io: Writing time: 0.03s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 144 primals, 384 duals
Objective: 4.83e+04
Solver model: available
Solver message: Optimal

Running HiGHS 1.11.0 (git hash: n/a): Copyright (c) 2025 HiGHS under MIT licence terms

('ok', 'optimal')